image: node:10.15.0
pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - npm install
            - npm test
  branches:
    master:
      - step:
          script:
            - npm install
            - npm test
